version: '3'
services:
  db:
   image: mysql:5.7
   environment:
     MYSQL_ROOT_PASSWORD: root
   volumes:
     - ./Data2:/var/lib/mysql
   ports:
     - 3307:3306
   container_name: mysqlarticulos

  tomcat:
    image: tomcat:9.0
    volumes:
      - ./Tomcat:/usr/local/tomcat/webapps
    ports:
      - 80:8080
    container_name: tomcat
