version: '3'
services:
  db-wildfly:
   image: mysql:5.7
   environment:
     MYSQL_ROOT_PASSWORD: root
   volumes:
     - ./Data2:/var/lib/mysql
   ports:
     - 3307:3306
   container_name: mysqlarticulos-wildfly

  wildfly:
    image: jboss/wildfly-admin
    volumes:
      - ./Wildfly:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 80:8080
      - 9990:9990
    container_name: wildfly
